sunshine_version: 0.20.0
distro: "{{ansible_distribution | lower}}"
distro_version: "{{ansible_distribution_version}}"
pkg_url: "https://github.com/LizardByte/Sunshine/releases/download/v{{ sunshine_version }}/sunshine-{{ distro }}-{{ distro_version }}-amd64.deb"