- name: Install dependencies
  ansible.builtin.apt:
    pkg:
    - libboost-chrono1.74.0
  become: true

- name: Download pkg
  ansible.builtin.get_url:
    url: "{{download_url}}"
    dest: "{{cache_dir}}/{{file_name}}"
    force: false

- name: Install .deb package
  ansible.builtin.apt:
    deb: "{{cache_dir}}/{{file_name}}"
  become: true
